### ISSUE TITLE
"Key already exists" message on foreman start

### ISSUE THREAD

**Issue by robfentress** [harvard-dce/canvas_vagrant#4]
I tried following your instructions to setup and run this Canvas Vagrant box, but when I went to the URL I got a connection refused error.  Here is what I entered at the command line on OS X and what was returned to me.  I'd appreciate any help you could give me.

canvas_vagrant-master > vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'harvard-dce/ubuntu-14-04-canvas-lms' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'harvard-dce/ubuntu-14-04-canvas-lms'
    default: URL: https://atlas.hashicorp.com/harvard-dce/ubuntu-14-04-canvas-lms
==> default: Adding box 'harvard-dce/ubuntu-14-04-canvas-lms' (v1.0.4) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/harvard-dce/boxes/ubuntu-14-04-canvas-lms/versions/1.0.4/providers/virtualbox.box
==> default: Successfully added box 'harvard-dce/ubuntu-14-04-canvas-lms' (v1.0.4) for 'virtualbox'!
==> default: Importing base box 'harvard-dce/ubuntu-14-04-canvas-lms'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'harvard-dce/ubuntu-14-04-canvas-lms' is up to date...
==> default: Setting the name of the VM: canvas_vagrant-master_default_1449583779640_93592
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/rfentres/Downloads/canvas_vagrant-master
canvas_vagrant-master > vagrant ssh
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-37-generic x86_64)
- Documentation:  https://help.ubuntu.com/
  
  System information as of Tue Dec  8 09:10:00 EST 2015
  
  System load:  0.6               Processes:           99
  Usage of /:   44.8% of 7.26GB   Users logged in:     0
  Memory usage: 5%                IP address for eth0: 10.0.2.15
  Swap usage:   0%                IP address for eth1: 192.168.50.4
  
  Graph this data and manage this system at:
    https://landscape.canonical.com/

Last login: Mon Oct 27 16:14:59 2014

---

To run canvas:

> cd ~/canvas-lms
> foreman start -f Procfile.dev

Wait about 30 seconds for the web interface to spin up, then it should
be available on:

http://192.168.50.4:3000/

username: vagrant@example.com
password: vagrant

---

Last commit on "master" branch:

commit 75fa1fe61318738d3798891c6c64596ac1b24b4f
Author: Michael Nomitch mnomitch@instructure.com
Date:   Mon May 18 15:29:30 2015 -0500

```
added semicolons to jsx to fix minification bug

Change-Id: Ib60496504253e14113d9dd2837ec3a054c68fefb
Reviewed-on: https://gerrit.instructure.com/55167
Tested-by: Jenkins
Reviewed-by: Ethan Vizitei <evizitei@instructure.com>
QA-Review: August Thornton <august@instructure.com>
Product-Review: Simon Williams <simon@instructure.com>
```

Happy canvassing!

vagrant@vagrant:~$ cd canvas-lms
vagrant@vagrant:~/canvas-lms$ foreman start -f Procfile.dev
09:11:39 web.1    | started with pid 2198
09:11:39 worker.1 | started with pid 2200
09:11:52 web.1    | => Booting Thin
09:11:52 web.1    | => Rails 3.2.21 application starting in development on http://0.0.0.0:3000
09:11:52 web.1    | => Call with -d to detach
09:11:52 web.1    | => Ctrl-C to shutdown server
09:11:53 worker.1 | /home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval': PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_settings_on_name" (ActiveRecord::RecordNotUnique)
09:11:53 worker.1 | DETAIL:  Key (name)=(encryption_key_hash) already exists.
09:11:53 worker.1 | : INSERT INTO "settings" ("created_at", "name", "updated_at", "value") VALUES ($1, $2, $3, $4) RETURNING "id"
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:1176:in`exec_cache'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `block in exec_query'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:280:in`block in log'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/sharded_instrumenter.rb:19:in`instrument'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/abstract_adapter.rb:20:in`log_with_timestamp'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:63:in`exec_insert'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:90:in `insert'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/query_cache.rb:68:in`insert'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:66:in `insert'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/active_record.rb:976:in`create'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/timestamp.rb:58:in `create'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/callbacks.rb:268:in`block in create'
09:11:53 worker.1 |     from (eval):3:in `run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in`instance_eval'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in`block in run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `block in scoping'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in`with_scope'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in `scoping'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in`run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/callbacks.rb:268:in `create'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/persistence.rb:348:in`create_or_update'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/callbacks.rb:264:in `block in create_or_update'
09:11:53 worker.1 |     from (eval):3:in`run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in `instance_eval'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/gems/activesupport-suspend_callbacks/lib/active_support/callbacks/suspension.rb:111:in`run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `block in run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in`block in scoping'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in `with_scope'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in`scoping'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/active_record.rb:1622:in `run_callbacks'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/callbacks.rb:264:in`create_or_update'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/persistence.rb:104:in `save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/validations.rb:56:in`save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:264:in`block in save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in`transaction'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:208:in `transaction'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:42:in`block in transaction'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/relation.rb:91:in `activate'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:37:in`transaction'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/transactions.rb:264:in`save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:90:in `block in save!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in`block in scoping'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/scoping.rb:98:in `with_scope'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activerecord/lib/active_record/relation.rb:241:in`scoping'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/switchman-1.2.35/lib/switchman/active_record/base.rb:90:in `save!'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/app/models/setting.rb:40:in`set'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/lib/canvas/security.rb:143:in `validate_encryption_key'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/initializers/canvas_security.rb:1:in`<top (required)>'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:245:in `load'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:245:in`block in load'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:245:in`load'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:592:in`each'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/engine.rb:592:in `block in <class:Engine>'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in`instance_exec'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:30:in `run'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:55:in`block in run_initializers'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in `each'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/initializable.rb:54:in`run_initializers'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/application.rb:136:in `initialize!'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/railties/lib/rails/railtie/configurable.rb:30:in`method_missing'
09:11:53 worker.1 |     from /home/vagrant/canvas-lms/config/environment.rb:11:in `<top (required)>'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in`require'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:236:in`load_dependency'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/rails-b344986bc3d9/activesupport/lib/active_support/dependencies.rb:251:in `require'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/canvas-jobs-0.9.13/lib/delayed/pool.rb:124:in`load_rails'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/canvas-jobs-0.9.13/lib/delayed/pool.rb:90:in `start'
09:11:53 worker.1 |     from /home/vagrant/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/canvas-jobs-0.9.13/lib/delayed/pool.rb:56:in`run'
09:11:53 worker.1 |     from script/delayed_job:10:in `<main>'
09:11:53 worker.1 | exited with code 1
09:11:53 system   | sending SIGTERM to all processes
09:11:53 web.1    | Exiting
09:11:53 web.1    | terminated by SIGTERM

**Comment by robfentress** [comment]
Nevermind.  Seems to work now.

**Comment by djcp** [comment]
Thanks for the update - I'll look into updating this box soon too.

**Comment by robfentress** [comment]
Great!
