### ISSUE TITLE
Thank you! Please tell me next step!

### ISSUE THREAD

**Issue by ihatov08** [harvard-dce/canvas_vagrant#6]
Thank you make this page!
I can see [sign in] page in vagrant.
But I can see only [sign in] page.
I want to go sign up page.
Plese teach how to go sign up page.

**Comment by djcp** [comment]
This project is about getting a test canvas running for you locally via vagrant, not to teach you how to use canvas.

If you're asking how to sign in, the default username / password for canvas is 

Username: `vagrant@example.com`
Password: `vagrant`

If your question is more about how to use canvas, I'd ask [here](https://community.canvaslms.com/welcome) for more help.

**Comment by ihatov08** [comment]
Thank you.
I'm sorry  in poor English

**Comment by djcp** [comment]
No problem! I just wasn't sure what you were looking for. I hope this project helps you!

**Comment by ihatov08** [comment]
I want to ask how to sign in!
It was the exact answer！
Thank you very much!
